source 'https://rubygems.org'

# Specify your gem's dependencies in biblio-domain.gemspec
gemspec

gem 'minitest', '~> 5.0'
gem 'rake', '~> 12.0'

gem 'dry-initializer'

gem 'rubocop', require: false
