source 'https://rubygems.org'

# Specify your gem's dependencies in biblio-domain.gemspec
gemspec

gem 'minitest', '~> 5.0'
gem 'rake', '~> 12.0'

gem 'dry-initializer'

group :development do
  gem 'rubocop', require: false
end

gem 'pg'
gem 'rom',     '~> 5.2'
gem 'rom-sql', '~> 3.2'
