require 'bundler/gem_tasks'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb']
  t.warning = false
end

task default: :test

require 'rom/sql/rake_task'
require 'rom'
require 'rom-sql'
require 'biblio/domain'

namespace :db do
  task :setup do
    ROM::SQL::RakeSupport.env = Biblio::Db::Config.migration_container
  end
end
