require 'bundler/gem_tasks'
require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb']
  t.warning = false
end

task default: :test

require 'rom/sql/rake_task'
require 'rom'
require 'rom-sql'

namespace :db do
  task :setup do
    # your ROM setup code
    # Usually something like this:
    opts = {
      host: '127.0.0.1',
      adapter: :sql,
      username: 'postgres',
      password: 'root',
      encoding: 'UTF8',
      migrator: {
        path: 'lib/biblio/db/migrate'
      }
    }

    ROM::SQL::RakeSupport.env = ROM.container(:sql, 'postgres://127.0.0.1:5432/bibliodb', opts)
  end
end
