require: rubocop-rails

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassVars:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

